import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ChevronDown,Clock3,Instagram,MapPin,Menu,MessageCircle,Play,ShieldCheck,Sparkles,Star,X} from 'lucide-react';
import './styles.css';

const WA='https://wa.me/5521999999999?text=Ol%C3%A1%2C%20Dra.%20Helena!%20Quero%20agendar%20uma%20consulta.';
const nav=[['Início','#inicio'],['Sobre mim','#sobre'],['Método','#metodo'],['Especialidades','#especialidades'],['Resultados','#resultados'],['Contato','#contato']];
const specialties=[
 ['Emagrecimento sustentável','Estratégia nutricional sem dietas radicais, com foco em rotina, saciedade e constância.'],
 ['Comportamento alimentar','Um olhar acolhedor para reduzir culpa, ansiedade e o ciclo de restrição e compulsão.'],
 ['Saúde da mulher','Planos individualizados para fases e necessidades específicas do corpo feminino.'],
 ['Performance & composição','Nutrição inteligente para quem treina e quer mais energia, recuperação e composição corporal.']
];
const faqs=[
 ['Como funciona a primeira consulta?','Começamos entendendo sua rotina, histórico, objetivos e relação com a alimentação. A partir disso, construímos uma estratégia prática e personalizada.'],
 ['A consulta é online ou presencial?','Você pode escolher entre atendimento online ou presencial. O acompanhamento mantém a mesma profundidade e cuidado nos dois formatos.'],
 ['Vou receber uma dieta pronta?','Você recebe um plano alimentar personalizado, mas o processo vai além de uma folha de dieta: trabalhamos comportamento, rotina, preferências e autonomia.'],
 ['Quanto tempo dura o acompanhamento?','A duração depende do seu objetivo. O acompanhamento é ajustado ao seu momento, com revisões e evolução progressiva.']
];

function App(){
 const [loading,setLoading]=useState(true),[progress,setProgress]=useState(0),[menu,setMenu]=useState(false),[open,setOpen]=useState(null);
 useEffect(()=>{const t=setInterval(()=>setProgress(p=>{if(p>=100){clearInterval(t);setTimeout(()=>setLoading(false),350);return 100}return Math.min(100,p+4)}),35);return()=>clearInterval(t)},[]);
 if(loading)return <div className="loader"><div className="loader-inner"><span className="eyebrow">NUTRIÇÃO CLÍNICA • COMPORTAMENTO • PERFORMANCE</span><div className="loader-name">Dra. Helena <i>Martins</i></div><div className="loader-line"><span style={{width:progress+'%'}}/></div><div className="loader-meta"><span>Preparando sua experiência</span><strong>{progress}%</strong></div></div></div>;
 return <div>
  <header className="header"><a className="brand" href="#inicio"><span>HM</span><div><b>Dra. Helena Martins</b><small>NUTRIÇÃO & COMPORTAMENTO</small></div></a><nav>{nav.map(([n,h])=><a key={h} href={h}>{n}</a>)}</nav><a className="header-cta" href={WA} target="_blank">Agendar consulta <ArrowUpRight size={16}/></a><button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  {menu&&<div className="mobile-nav">{nav.map(([n,h])=><a onClick={()=>setMenu(false)} href={h} key={h}>{n}</a>)}<a className="mobile-wa" href={WA}>Falar no WhatsApp</a></div>}
  <main>
   <section id="inicio" className="hero">
    <div className="hero-copy"><span className="eyebrow light">NUTRIÇÃO COM CIÊNCIA, ACOLHIMENTO E ESTRATÉGIA</span><h1>Seu corpo não precisa de <em>mais uma dieta.</em><br/>Precisa de um plano que caiba na sua vida.</h1><p>Nutrição individualizada para você emagrecer, cuidar da saúde e construir uma relação mais leve com a comida — sem extremismos.</p><div className="hero-actions"><a className="btn btn-primary" href={WA} target="_blank">Quero transformar minha rotina <ArrowUpRight/></a><a className="text-link" href="#metodo"><Play size={15}/> Conheça meu método</a></div><div className="proof"><div className="avatars"><span>AM</span><span>JL</span><span>RF</span></div><div><div className="stars">★★★★★</div><small>+ de 500 pacientes acompanhados</small></div></div></div>
    <div className="hero-image"><div className="hero-card"><strong>Consulta personalizada</strong><span>Online • Presencial</span><small>Vagas para novos acompanhamentos</small></div></div>
    <div className="hero-scroll">SCROLL <span/></div>
   </section>
   <section className="trust"><div><b>+500</b><span>pacientes acompanhados</span></div><div><b>8 anos</b><span>de experiência clínica</span></div><div><b>4.9/5</b><span>avaliação média</span></div><div><b>100%</b><span>plano individualizado</span></div></section>
   <section id="sobre" className="about section"><div className="about-photo"><img src="https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=900&q=85" alt="Nutricionista em ambiente clínico"/><div className="photo-tag"><Sparkles size={17}/><span>CRN 00000<br/><b>Nutrição clínica</b></span></div></div><div className="about-copy"><span className="eyebrow">SOBRE MIM</span><h2>Nutrição sem terrorismo. <em>Com estratégia.</em></h2><p className="lead">Eu acredito que cuidar da alimentação não deveria transformar sua vida em uma lista de proibições.</p><p>Sou a Dra. Helena Martins, nutricionista clínica, e há anos ajudo pessoas a construírem resultados que permanecem depois da consulta. Meu trabalho une ciência, escuta e ferramentas práticas para que você saiba exatamente o que fazer — e, principalmente, por que está fazendo.</p><div className="signature">Helena Martins <small>Nutricionista clínica</small></div><a className="outline-link" href={WA}>Conheça meu atendimento <ArrowUpRight size={16}/></a></div></section>
   <section id="metodo" className="method section"><div className="section-head"><div><span className="eyebrow">MEU MÉTODO</span><h2>Menos cobrança.<br/><em>Mais direção.</em></h2></div><p>Um processo estruturado para transformar conhecimento em comportamento — respeitando seu corpo, sua rotina e seus objetivos.</p></div><div className="steps">{[['01','Entender','Mapeamos sua história, rotina, exames, preferências e o que realmente está por trás do seu objetivo.'],['02','Estruturar','Criamos uma estratégia alimentar personalizada, possível e baseada em evidências.'],['03','Acompanhar','Ajustamos o plano conforme sua evolução, sem deixar você sozinho no caminho.'],['04','Consolidar','Você desenvolve autonomia para manter seus resultados com segurança e leveza.']].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><ArrowUpRight className="step-arrow"/></div>)}</div></section>
   <section id="especialidades" className="special section"><div className="section-head"><div><span className="eyebrow">ESPECIALIDADES</span><h2>Seu objetivo.<br/><em>Meu compromisso.</em></h2></div><p>Atendimento individualizado para diferentes momentos da vida, sempre com uma estratégia construída para você.</p></div><div className="special-grid">{specialties.map(([t,d],i)=><article key={t}><span className="num">0{i+1}</span><h3>{t}</h3><p>{d}</p><a href={WA}>Saiba mais <ArrowUpRight size={15}/></a></article>)}</div></section>
   <section className="manifesto"><div><span className="eyebrow light">UMA NOVA FORMA DE OLHAR PARA A NUTRIÇÃO</span><h2>“Resultado de verdade é aquele que você consegue <em>viver.</em>”</h2><p>Não buscamos a rotina perfeita. Buscamos uma rotina que funcione.</p></div></section>
   <section id="resultados" className="results section"><div className="section-head"><div><span className="eyebrow">EXPERIÊNCIAS REAIS</span><h2>O que muda quando<br/><em>você tem direção.</em></h2></div><a className="outline-link" href={WA}>Quero começar <ArrowUpRight size={16}/></a></div><div className="testimonials"><article><div className="stars">★★★★★</div><p>“Pela primeira vez eu não senti que estava fazendo dieta. Aprendi a comer de um jeito que consigo manter mesmo nos dias corridos.”</p><b>Mariana R.</b><small>Paciente • acompanhamento 8 meses</small></article><article><div className="stars">★★★★★</div><p>“O atendimento é extremamente humano e, ao mesmo tempo, muito técnico. Meu relacionamento com a comida mudou completamente.”</p><b>Camila S.</b><small>Paciente • acompanhamento 6 meses</small></article><article><div className="stars">★★★★★</div><p>“Eu queria emagrecer, mas saí entendendo muito mais sobre meu corpo. Resultado com leveza e sem viver pensando em dieta.”</p><b>Rafael M.</b><small>Paciente • acompanhamento 5 meses</small></article></div></section>
   <section className="gallery section"><div className="gallery-intro"><span className="eyebrow">UM ESPAÇO PARA VOCÊ</span><h2>Seu cuidado começa<br/><em>antes da consulta.</em></h2><p>Um ambiente pensado para trazer acolhimento, privacidade e uma experiência à altura do seu momento.</p><a className="btn btn-dark" href={WA}>Agendar meu horário <ArrowUpRight/></a></div><div className="gallery-images"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85" alt="Consultório"/><img src="https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=700&q=85" alt="Alimentação saudável"/><img src="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=700&q=85" alt="Refeição saudável"/></div></section>
   <section className="faq section"><div><span className="eyebrow">DÚVIDAS FREQUENTES</span><h2>Antes de<br/><em>começar.</em></h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={'faq-item '+(open===i?'open':'')} key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><ChevronDown/></button>{open===i&&<p>{a}</p>}</div>)}</div></section>
   <section id="contato" className="contact"><div className="contact-main"><span className="eyebrow light">PRONTO PARA COMEÇAR?</span><h2>Vamos construir uma relação mais leve com a <em>alimentação.</em></h2><p>Agende sua consulta e dê o primeiro passo com um plano pensado para você.</p><a className="btn btn-light" href={WA} target="_blank"><MessageCircle/> Falar com a Dra. Helena <ArrowUpRight/></a></div><div className="contact-info"><div><MapPin/><span><b>Atendimento presencial</b>Av. das Américas, 5000<br/>Barra da Tijuca • Rio de Janeiro</span></div><div><Clock3/><span><b>Horários</b>Seg a Sex • 08h às 19h<br/>Sáb • 08h às 13h</span></div><div><MessageCircle/><span><b>WhatsApp</b>(21) 99999-9999</span></div></div></section>
  </main>
  <footer><div className="footer-brand"><span>HM</span><div><b>Dra. Helena Martins</b><small>NUTRIÇÃO & COMPORTAMENTO</small></div></div><p>Nutrição baseada em ciência, estratégia e acolhimento.</p><div className="footer-links"><a href="#inicio">Início</a><a href="#sobre">Sobre</a><a href="#especialidades">Especialidades</a><a href="#contato">Contato</a><a href="https://instagram.com" target="_blank"><Instagram size={17}/></a></div><small>© 2026 Dra. Helena Martins. Todos os direitos reservados.</small></footer>
  <a className="floating-wa" href={WA} target="_blank" aria-label="WhatsApp"><MessageCircle/><span>Fale comigo</span></a>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);